### ISSUE TITLE
diozero on gradle?

### ISSUE THREAD

**Issue by Ghozti** [mattjlewis/diozero#101]
I am interested in using diozero on my current project with pi4j however, is there any way to use this library using Gradle?

**Comment by Reqeique** [comment]
https://mvnrepository.com/artifact/com.diozero/diozero-core/1.3.3 you can find maven repos for gradle too

**Comment by mattjlewis** [comment]
Exactly - I've created a test project that uses Gradle here: https://github.com/mattjlewis/diozero-gradle-app
