### ISSUE TITLE
System-utils-native pollutes stdin

### ISSUE THREAD

**Issue by BartoszKaszewczuk** [mattjlewis/diozero#13]
`system-utils-native` contains C files that log diagnostic info to console using `printf()` statements. It obviously helps when debugging the application but at the same time it happens to pollute `stdin` use of which isn't uncommon when it comes to simple IO in embedded applications hence forcing user to implement additional `stdin` filtering to account for that. 

A simple example where this could observed:
```java
Button button = new Button(0, GpioPullUpDown.PULL_UP);
LED led = new LED(2);
button.whenPressed(led::toggle);
```

Outputs following to console (In this case `stop()...` clauses seem to originate from `com_diozero_util_PollNative.c`):
```
system-utils-native JNI_OnLoad
stop(): closing fd 0
stop(): closing fd 0
```

If we extend that code example to accept stdin from `Scanner` like so:
```java
Button button = new Button(0, GpioPullUpDown.PULL_UP);
LED led = new LED(2);
button.whenPressed(led::toggle);

Scanner in = new Scanner(System.in);
in.nextLine();
```

Then we end up with a case where `system-utils-native`'s pollution causes `java.util.NoSuchElementException` unless user explicitly filters stdin or handles it some other way.

```
system-utils-native JNI_OnLoad
stop(): closing fd 0
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at com.Test.Main.main(Main.java:20)
```

Handling logging from `system-utils-native` using some logging lib would probably be the best solution however perhaps some of those statements are redundant?

**Comment by mattjlewis** [comment]
You're absolutely right. I've checked in updated code and rebuilt the library for the Raspberry Pi. I'll close the issue once I've rebuilt the library for the other supported platforms.
