### ISSUE TITLE
Enhancement: AbstractDeviceFactory can "register" devices

### ISSUE THREAD

**Issue by EAGrahamJr** [mattjlewis/diozero#131]
There are several methods used with the `DeviceStates` internal class to determine whether or not devices are "opened" or not (`isDeviceOpened`, `deviceOpened`, `deviceClosed`). 

`deviceClosed` is actually invoked by the `AbstractDevice`. However, there is no "automatic" (or semi-automatic) means to utilized the _other_ two associated functions.

This issue is to track the addition of a method to the `AbstractDeviceFactory` for implementations to easily track device open/close.

**Comment by EAGrahamJr** [comment]
I see this is actually managed in sub-classes of this factory - closing.

**Comment by mattjlewis** [comment]
np - this internal aspect has evolved a bit over the years - doing my best to provide a completely seamless user experience and handle all of the device cleanup stuff.
