### ISSUE TITLE
Refactor DeviceFactory interfaces to use a default registration method and Supplier

### ISSUE THREAD

**Issue by EAGrahamJr** [mattjlewis/diozero#132]
There's a bit of repetitious code in the various `DeviceFactoryInterface` definitions that would benefit from consolidation. This involves mostly the "open" check and the ability to prevent duplicate devices from being created.

Recommendation: create a `default registerDevice` method that wraps the actual device creation in a `Supplier` so that all downstream classes do not have to check for open devices.

**Comment by EAGrahamJr** [comment]
(I've got this - it can definitely wait for 1.4)

**Comment by mattjlewis** [comment]
Brilliant - look forward to seeing something here. You might have seen I did a commit not so long ago refactoring some internal bits and pieces. I should really make use of the GitHub project board for tracking backlog / ideas...

**Comment by EAGrahamJr** [comment]
:grinning:
