### ISSUE TITLE
Probable bug in new StepperMotor setups

### ISSUE THREAD

**Issue by EAGrahamJr** [mattjlewis/diozero#148]
In the process of applying stepper functions to an expansion board, it appears that the 1.4 implementation isn't actually "correct" vis-a-vis what is supplied via Adafruit - the notion of what constitutes a step is pretty "simple" for the Python implementation, which is calling my previous efforts into doubt.

Please assign to me :smirk: if you wish.

**Comment by EAGrahamJr** [comment]
One apparent difference is the Adafruit library considers a "step" to be somewhat differently defined than what is defined in spec sheets.

For example, the `28BYJ-48` is nominally 512 "steps" for a complete rotation. This calls for 4 cycles across the 4 pins in order to get the 1/512 step, or 2048 "quarter steps", which is what the Adafruit library is calling a step all by itself.

**Comment by mattjlewis** [comment]
Thank you

**Comment by EAGrahamJr** [comment]
Close - this turns out to be essentially a duplicate of #147 (see notes there).
