### ISSUE TITLE
Add board info support for Raspberry Pi 5

### ISSUE THREAD

**Issue by EAGrahamJr** [mattjlewis/diozero#184]
Just announced -- https://www.raspberrypi.com/products/raspberry-pi-5/ :sunglasses:

**Comment by mattjlewis** [comment]
Pre-ordered today ;-)

**Comment by EAGrahamJr** [comment]
Saving my :moneybag: for Xmas...

**Comment by mattjlewis** [comment]
Should now all work with latest code.
