### ISSUE TITLE
DigitalOutputDevice.setValueUnsafe() 

### ISSUE THREAD

**Issue by fpompermaier** [mattjlewis/diozero#2]
In the class DigitalOutputDevice there's the following method. Is it safe to rely on it?
Can you explain better that Javadoc?

Thanks in advance,
Flavio

```
/**
 * Unsafe operation that has no synchronisation checks and doesn't factor in active low logic.
 * Included primarily for performance tests
 * @param value the new value
 * @throws RuntimeIOException if an I/O error occurs
 */
public void setValueUnsafe(boolean value) throws RuntimeIOException {
	device.setValue(value);
}
```

**Comment by mattjlewis** [comment]
Yes entirely safe to use this method. It would possibly be better named as setValueRaw. I use it for performance tests as there is no synchronisation or compensating for active high / low logic.
