### ISSUE TITLE
DeviceFactoryHelper error

### ISSUE THREAD

**Issue by avysochin** [mattjlewis/diozero#29]
Tinker board have the error: DeviceFactoryHelper.init - Using native factory class **SysFsDeviceFactory** after adding Java Device I/O JAR to my local Maven repository, the error changes to another: DeviceFactoryHelper.init - Using native factory class **JdkDeviceIoDeviceFactory.**  Also there is LibraryLoader.loadlibrary - Loaded library 'diozero-system-utils' from classpath exception. GPIO_C_Library installed, and directly from the shell GPIO is working excellent.

**Comment by mattjlewis** [comment]
Hi, could you be more specific on the error please.

Regards,
Matt

**Comment by avysochin** [comment]
i think Java Device I/O and Diozero working separately from each other. How need to connect it ?

**Comment by mattjlewis** [comment]
Question - why do you want to use JDK Device I/O? Try running with just diozero-core (and tinylog) first.
Regards,
Matt

**Comment by avysochin** [comment]
How Diozero select in what board have been running? Rpi, BB or Tinker. i think Java Device I/O with wiringpi, pi4j is one of a providers for Diozero. Or not ?

**Comment by mattjlewis** [comment]
diozero automatically detects the board it is running on. The builtin "sysfs" provider works on all boards that I list as supported. You don't actually need to use pi4j / wiringpi or any of the other providers.

Matt

**Comment by avysochin** [comment]
DeviceFactoryHelper.init - Using native factory class SysFsDeviceFactory 
LibraryLoader.loadlibrary - Loaded library 'diozero-system-utils' from classpath 
are not error but only debug because maven run with -e flag

**Comment by mattjlewis** [comment]
Please move this discussion to the [Google Group](https://groups.google.com/forum/#!forum/diozero) as I don't believe this is an issue with diozero.
