### ISSUE TITLE
DeviceFactoryHelper

### ISSUE THREAD

**Issue by avysochin** [mattjlewis/diozero#30]
Why Maven could not find the package com.diozero.util.DeviceFactoryHelper in SystemInfoTest.java
example? When i have put sources diozero/util/*.java to my local project directory - the error disappear.

**Comment by mattjlewis** [comment]
How are you running this test - can you share the command line please.

**Comment by avysochin** [comment]
mvn exec:java -Dexec.mainClass="tinkerexample.App",

**Comment by mattjlewis** [comment]
Ah, ok. Please use just diozero-core and not diozero-provider-sysfs. diozero-provider-sysfs was merged into diozero-core.
See the following documentation page: [Creating Your Own diozero Application](http://www.diozero.com/en/latest/Application/).
Matt

**Comment by avysochin** [comment]
Dear Matt

cut the pom - file
<dependency>
	    <groupId>com.diozero</groupId>
	    <artifactId>diozero-core</artifactId>
	    <version>0.10</version>
</dependency>

have delete sources files diozero/util/*.java from my local project directory 
the run
mvn compile

Error: cannot find symbol: class DeviceFactoryHelper
Location: package com.diozero.util

**Comment by mattjlewis** [comment]
Glad to hear it is now working, let me know of any other issues.
