### ISSUE TITLE
JVM crash on exit when using WS2812 on RPi Zero W

### ISSUE THREAD

**Issue by Zappes** [mattjlewis/diozero#39]
I've just started writing an application for the RPi Zero W that uses a WS2812 strip. When creating my rudimentary service, I noticed that the JVM reproducibly crashes when the WS281x is closed.

I have attached the error log created by the JVM: [hs_err_pid909.log](https://github.com/mattjlewis/diozero/files/2260091/hs_err_pid909.log)

The code that caused this crash on exit can be found here: https://github.com/Zappes/Henkinson/blob/master/src/main/java/net/bluephod/henkinson/Henkinson.java (commit 2f46b54)

Great library BTW - I really like it a lot!

**Comment by mattjlewis** [comment]
Thanks and apologies for the very (!) long delay replying. Does this crash still happen? I've just committed a new snapshot build (0.12-SNAPSHOT) that includes an updated version of the ripws281x native library. BTW, I also implemented a pure Java version that uses SPI.

**Comment by mattjlewis** [comment]
This should now be fixed.
