### ISSUE TITLE
Forked repo, can't build because of missing dependencies

### ISSUE THREAD

**Issue by Zappes** [mattjlewis/diozero#40]
I just forked the repo as I consider contributing to the code base. When I try to build with `mvn clean install`, the build fails because jdk.dio:device-io:jar:1.0 can't be found. A log of the build is attached: 
[build.log](https://github.com/mattjlewis/diozero/files/2260096/build.log)

Do I have to do something specific prior to building the project? If that should be the case, it would be extremely helpful if a little help was provided in the README.

**Comment by Zappes** [comment]
A closer look shows that some more dependencies can't be found in Maven Central:

![diozero-missing-deps](https://user-images.githubusercontent.com/6427402/43683598-99d56118-988f-11e8-93d4-2216b2661bee.png)

**Comment by Sergeant007** [comment]
Same with me. I have few ideas with code improvements, but postpone them, since I cannot build the project.

**Comment by Sergeant007** [comment]
Is this possible just to move JDK providers to a separate GitHub repo? Documentation says:
> In theory the OpenJDK Device I/O service provider should provide the best platform support, however, the JDK Device I/O library doesn't support PWM. 

Absence of software PWM, publicly accessible Maven artifact and slow development activity (one commit per 2 months to http://hg.openjdk.java.net/dio/dev) could probably mean that OpenJDK Device I/O is not mature enough to be used.

**Comment by mattjlewis** [comment]
Resolved in 0.12-SNAPSHOT
