### ISSUE TITLE
mfrc522: ReadAndWrite Example

### ISSUE THREAD

**Issue by giuseppCl** [mattjlewis/diozero#45]
Hi there, 

i'm using your mfrc522 sampleapps to learn a bit about  the Reader/Writer. 
I can successfully read data from secotr's/blocks but i'm not able to write data.
I want to change the access bits of the sector trailer in sector 1 so that i 'm able to increment the block 0 of sector 1

**My changes:**

Changed boolean from false to true. 
`readAndWrite(rfid, uid, auth_key, true);`

I choosed sector 1 
```
                byte blocks_per_sector = 4;
		byte sector = 6;
		byte blockAddr = (byte) (sector * blocks_per_sector + 3);  //Sector Trailer Addr
		byte trailerBlock = (byte) (blockAddr + (blocks_per_sector - 1));
```

and my datablock is

```
//Default settings: KeyA&B = FFFF FFFF FFFF h ----- Access Bits = FF0780 h
//Structure Sector Trailer: KEYA(6Byte) ------- ACCESSBITS(3Byte)+USerData(1Byte)-----KEYB(6Byte)
//My Data Block: Key A ------ AccessBits: EE178100 h ------- Key B
byte[] dataBlock = {											
	(byte )0xff, (byte )0xff,(byte )0xff, (byte )0xff,		
	(byte )0xff,(byte )0xff, (byte)0xee, 0x17,				
	(byte)0x81, 0x00, (byte) 0xff, (byte )0xff,
	(byte )0xff, (byte )0xff, (byte )0xff, (byte )0xff
};
```

**This is the error message:**

> sudo java -cp tinylog-1.3.6.jar:diozero-core-0.12-SNAPSHOT.jar:RFID.jar:diozero-provider-pigpio-0.12-SNAPSHOT.jar:pigpioj-java-2.2.jar:httpcore-4.4.11.jar:httpclient-4.5.8.jar:commons-logging-1.2.jar:commons-codec-1.11.jar:org.eclipse.paho.client.mqttv3-1.0.2.jar com.diozero.sampleapps.mfrc522.ReadAndWrite 8 0 25 FFFFFFFFFFFF
15:37:44.116 [main] DEBUG com.diozero.util.DeviceFactoryHelper.init - Using native device factory class PigpioJDeviceFactory
15:37:44.156 [main] INFO com.diozero.internal.provider.pigpioj.PigpioJDeviceFactory.initialiseBoardInfo - Hardware revision: 10494163 (0xa020d3)
15:37:44.251 [main] DEBUG com.diozero.internal.provider.pigpioj.PigpioJSpiDevice.<init> - SPI device (8-0) opened, handle=0
15:37:44.254 [main] DEBUG com.diozero.devices.MFRC522.init - reset pin was off
15:37:44.278 [main] DEBUG com.diozero.util.LibraryLoader.loadLibrary - Loaded library 'diozero-system-utils' from classpath
15:37:44.337 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.main - Scanning for RFID tags...
15:37:45.378 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - timer interrupt, n: 0x45
15:37:45.379 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Timed out waiting for interrupt
15:37:46.388 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 2
15:37:46.389 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.390 [main] DEBUG com.diozero.devices.MFRC522.select - uid_complete: false, cascade_level: 1
15:37:46.391 [main] DEBUG com.diozero.devices.MFRC522.select - select_done: false
15:37:46.392 [main] DEBUG com.diozero.devices.MFRC522.select - ANTICOLLISION: current_level_known_bits=0
15:37:46.393 [main] DEBUG com.diozero.devices.MFRC522.select - tx_last_bits: 0
15:37:46.420 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 5
15:37:46.421 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.422 [main] DEBUG com.diozero.devices.MFRC522.select - select_done: false
15:37:46.423 [main] DEBUG com.diozero.devices.MFRC522.select - SELECT: current_level_known_bits=32
15:37:46.424 [main] DEBUG com.diozero.devices.MFRC522.select - tx_last_bits: 0
15:37:46.427 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 3
15:37:46.427 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.433 [main] DEBUG com.diozero.devices.MFRC522.select - End of while (!uidComplete) loop, uid: UID [uidBytes=6B2A4C0B, sak=8]
15:37:46.438 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.main - Found card with UID 0x6B2A4C0B, type: MIFARE_1K
15:37:46.439 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Authenticating using key A...
15:37:46.440 [main] DEBUG com.diozero.devices.MFRC522.authenticate - blockAddr: 27
15:37:46.443 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.444 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Current data in sector:
   6     27  15:37:46.446 [main] DEBUG com.diozero.devices.MFRC522.authenticate - blockAddr: 24
15:37:46.449 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.449 [main] DEBUG com.diozero.devices.MFRC522.mifareRead - blockAddr: 27
15:37:46.452 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 18
15:37:46.453 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Checking CRC
15:37:46.454 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
 00 00 00 00  00 00 ff 07  80 69 ff ff  ff ff ff ff  [ 0 0 1 ] 
         26  15:37:46.458 [main] DEBUG com.diozero.devices.MFRC522.mifareRead - blockAddr: 26
15:37:46.461 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 18
15:37:46.462 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Checking CRC
15:37:46.463 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         25  15:37:46.467 [main] DEBUG com.diozero.devices.MFRC522.mifareRead - blockAddr: 25
15:37:46.470 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 18
15:37:46.471 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Checking CRC
15:37:46.472 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
         24  15:37:46.476 [main] DEBUG com.diozero.devices.MFRC522.mifareRead - blockAddr: 24
15:37:46.479 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 18
15:37:46.480 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Checking CRC
15:37:46.481 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
15:37:46.485 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Reading data from block 0x1b ...
15:37:46.486 [main] DEBUG com.diozero.devices.MFRC522.mifareRead - blockAddr: 27
15:37:46.489 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 18
15:37:46.490 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - Checking CRC
15:37:46.490 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.491 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Data in block 0x1b : 0x00000000 0000FF07 8069FFFF FFFFFFFF D455
15:37:46.492 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Authenticating again using key B...
15:37:46.492 [main] DEBUG com.diozero.devices.MFRC522.authenticate - blockAddr: 27
15:37:46.495 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.496 [main] INFO com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - Writing data into block 0x1b : 0xFFFFFFFF FFFFEE17 8100FFFF FFFFFFFF ...
15:37:46.497 [main] ERROR com.diozero.sampleapps.mfrc522.ReadAndWrite.readAndWrite - MIFARE_Write() failed: INVALID
15:37:46.499 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - FIFO Level: 1
15:37:46.500 [main] DEBUG com.diozero.devices.MFRC522.communicateWithPICC - ok
15:37:46.501 [main] DEBUG com.diozero.api.SpiDevice.close - close()
15:37:46.502 [main] DEBUG com.diozero.internal.provider.AbstractDevice.close - close(), key=Native-SPI-8-0
15:37:46.503 [main] DEBUG com.diozero.internal.DeviceStates.closed - closed(Native-SPI-8-0)
15:37:46.510 [DIO-Zero Shutdown Handler] DEBUG com.diozero.util.ShutdownHandlerThread.run - Shutdown handler running
15:37:46.515 [DIO-Zero Shutdown Handler] DEBUG com.diozero.internal.provider.AbstractDeviceFactory.close - close()
15:37:46.516 [DIO-Zero Shutdown Handler] DEBUG com.diozero.internal.DeviceStates.closeAll - closeAll()
15:37:46.525 [DIO-Zero Shutdown Handler] DEBUG com.diozero.internal.provider.AbstractDevice.close - close(), key=Native-GPIO-25
15:37:46.526 [DIO-Zero Shutdown Handler] DEBUG com.diozero.internal.provider.pigpioj.PigpioJDigitalOutputDevice.closeDevice - closeDevice()
15:37:46.527 [DIO-Zero Shutdown Handler] DEBUG com.diozero.internal.DeviceStates.closed - closed(Native-GPIO-25)
15:37:46.543 [DIO-Zero Shutdown Handler] DEBUG com.diozero.util.ShutdownHandlerThread.run - Shutdown handler finished

I tried to figure out on my own. So i looked up the implementation of the method:

`status = rfid.mifareWrite(blockAddr, dataBlock);
`
```
public StatusCode mifareWrite(byte blockAddr, byte[] buffer) {
		// Sanity check
		if (buffer == null || buffer.length != 16) {
			return StatusCode.INVALID;
		}
		
		// Mifare Classic protocol requires two communications to perform a write.
		// Step 1: Tell the PICC we want to write to block blockAddr.
		byte[] cmdBuffer = { PiccCommand.MF_WRITE.getValue(), blockAddr };
		StatusCode result = mifareTransceive(cmdBuffer); // Adds CRC_A and checks that the response is MF_ACK.
		if (result != StatusCode.OK) {
			return result;
		}
		
		// Step 2: Transfer the data
		return mifareTransceive(buffer); // Adds CRC_A and checks that the response is MF_ACK.
	} // End MIFARE_Write()
```
I think this method throws SatusCode Invalid when the byte Array is Null or whether its length is not equal 16. But thats not the case. 

thank you in advance

**Comment by jimontoyag** [comment]
It seems the problem is in the method 
`public StatusCode mifareTransceive(byte[] sendData, boolean acceptTimeout) {
		// Sanity check
		if (sendData == null || sendData.length != 16) {
			return StatusCode.INVALID;
		}`
Because in the mifareWrite he is sending this array `byte[] cmdBuffer = { PiccCommand.MF_WRITE.getValue(), blockAddr };` to the sendData parameter.
Maybe replace that block with communicateWithPICC to send the MF_READ instruction?

**Comment by giuseppCl** [comment]
Hi, thank you for your advice.
I solved this problem by commenting out 

`
	// Sanity check
		if (buffer == null || buffer.length != 16) {
			return StatusCode.INVALID;
		}
`
Due to that i'm able to change the access bits in the sector trailer.

**Comment by mattjlewis** [comment]
Excellent, thank you. I will incorporate into the other fixes that I have been making recently.
