### ISSUE TITLE
Can't find repository for artifact

### ISSUE THREAD

**Issue by AixNPanes** [mattjlewis/diozero#58]
I'm trying to build the project on a Raspberry Pi 3B+ running Fedora 32. In trying to build from source, I have a problem in diozero-imu-visualiser:

[ERROR] Failed to execute goal on project diozero-imu-visualiser: Could not resolve dependencies for project com.diozero:diozero-imu-visualiser:jar:0.14-SNAPSHOT: Failure to find interactivemesh.org:3dsModelImporterJFX:jar:0.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I cannot find a repository for 3dsModelImporterJFX

**Comment by mattjlewis** [comment]
I need to remove that from the build. Run this:

mvn install:install-file -Dfile=diozero-imu-visualiser/lib/jim3dsModelImporterJFX.jar -DgroupId=interactivemesh.org -DartifactId=3dsModelImporterJFX -Dversion=0.7 -Dpackaging=jar

Regards,
Matt
