### ISSUE TITLE
GPIO input debouncing

### ISSUE THREAD

**Issue by fpompermaier** [mattjlewis/diozero#6]
Do you have any strategy to fix this annoying problem?
If yes just tell me where to start and I'll try to issue a PR for it if it's not too complicated

**Comment by mattjlewis** [comment]
You could try using the SmoothedInputDevice? I've googled this a few times and not come across a satisfactory answer yet.

**Comment by fpompermaier** [comment]
Which is the difference between SmoothedInputDevice and Button?

**Comment by mattjlewis** [comment]
Thought you might ask that. Button has the convenience methods isPressed / whenPressed which simply wrap isActive / whenActive. I need to create a class inheritance diagram to illustrate.
One option is for Button to extend SmoothedInputDevice thereby getting debounce support (I think).
Could you try using SmoothedInputDevice and let me know if it provides you the right level of input debouncing. Like I say the only difference the renaming of active / inactive to pressed / released for convenience and representation of button vocabulary.

**Comment by fpompermaier** [comment]
I tried to use SmoothedInputDevice  but I didn't find a valuable solution..it seems that events sometimes are not triggered while some other time they are fired 2 or 3 times :(
This happens also with Buttons. Is there a way to get exactly one event on raining/falling edge of the input?

**Comment by mattjlewis** [comment]
Have a look at the SmoothedInputTest class in the test package (https://github.com/mattjlewis/diozero/blob/master/diozero-core/src/test/java/com/diozero/SmoothedInputTest.java) - I've just rerun this with some minor changes to the parameters and can see events being smoothed correctly.
What library are you using as the diozero system provider?

**Comment by fpompermaier** [comment]
I'm using jdkdio11

**Comment by mattjlewis** [comment]
I don't have an issue with Buttons on the Raspberry Pi, using any of the providers. It could be an issue with JDK Device I/O - do you have code where this does work?
Check this page for my wiring and code that I use to validate on the Pi: http://rtd.diozero.com/en/latest/InputDevices/#input-devices

**Comment by fpompermaier** [comment]
You're right, using  button.whenPressed() worked like a charm :+1:
