### ISSUE TITLE
MFRC522, setAntennaGain(..) has no effect 

### ISSUE THREAD

**Issue by lglowania** [mattjlewis/diozero#71]
I'm trying to increase the reading-range of my MFRC522. By using `MFRC522.getPiccType(sak);` i determined my picc is a MIFARE_1K. The data sheet (https://www.mouser.com/datasheet/2/302/MF1S503x-89574.pdf) says:

*Operating distance up to 100 mm
depending on antenna geometry and
reader configuration*

So i assume the antenna gain setting is available in general. But using `mfrc522.setAntennaGain(..)` seems to do nothing, the reading-range remains at ~20mm, no matter what AntennaGain-enum is passed. And `mfrc522.getAntennaGain()` returns always *null*.

Do you have a hint? Thank you.

**Comment by mattjlewis** [comment]
Please test with 1.2.3 and let me know if it fixes the issue.

**Comment by lglowania** [comment]
Yes, getAntennaGain() now returns the expected result.

**Comment by mattjlewis** [comment]
Excellent, thank you. Did it make a difference in range?

**Comment by lglowania** [comment]
Sorry for the late response. I had no time to investigate further. In my experiments it did not make any difference in range, but when  i used `mfrc522.setAntennaGain(AntennaGain.DB_48)` i frequently received read errors when placing the transponder. I don't remember exactly the error-output. It was something like `read error on 0x01`. I will comment my insights here in the future.
