### ISSUE TITLE
Writing Individual Pins

### ISSUE THREAD

**Issue by Seggan** [mattjlewis/diozero#72]
Hey, I don' think issues is the right place for this (I suggest opening discussions), but I don't thiink there is a way to individually flip GPIO pins? Maybe `RaspberryPiBoardInfoProvider.lookupByRevision(LocalSystemInfo.getInstance().getRevision()).createMmapGpio()`?

**Comment by mattjlewis** [comment]
Hi, I'm not sure what you are asking for here - is it simply to toggle a GPIO? If so, create a DigitalOutputDevice and invoke toggle.

Regarding Discussions - thanks for the reminder, have enabled now.

**Comment by Seggan** [comment]
I want the ability to turn on/off the pin I specify. Also might want to convert this to a discussion.

**Comment by mattjlewis** [comment]
Please do.
