### ISSUE TITLE
It is not possible to use DebouncedDigitalInputDevice with custom DeviceFactory (e.g. MCP23017)

### ISSUE THREAD

**Issue by jozala** [mattjlewis/diozero#88]
I would like to use digital input connected through MCP23017 expander with a debounce. 
With a current API it is possible to create only `DebouncedDigitalInputDevice` with `DeviceFactoryHelper.getNativeDeviceFactory()`.

I believe it is possible to implement additional constructor in for `DebouncedDigitalInputDevice` class which would accept `GpioDeviceFactoryInterface` and pass it to the `DigitalInputDevice` parent class constructor. 
Could you please confirm this would be correct approach?

**Comment by mattjlewis** [comment]
Good spot, I will address in 1.3.2 and release shortly. Thanks for raising.

**Comment by mattjlewis** [comment]
Should now be addressed.
