### ISSUE TITLE
Alt Fucntion on GPIO

### ISSUE THREAD

**Issue by neil-benn** [mattjlewis/diozero#90]
Hello,

  Is there a way to set the alt function of a gpio from within diozero?  I'm trying to keep within diozero as much as possible without resorting to calling system functions.

Cheers,

Neil

**Comment by mattjlewis** [comment]
Hi Neil, this would be a great feature enhancement. In the short term I could very easily extend the low-level API [here](https://github.com/mattjlewis/diozero/blob/main/diozero-core/src/main/java/com/diozero/internal/board/raspberrypi/RaspberryPiMmapGpio.java#L231) to allow this. At the moment it only supports setting to digital input / output and PWM. It would be trivial to extend this class to add a method that allows any mode to be set on the assumption that the caller is responsible for specifying a valid mode.

Something like:
```public void setMode(int gpio, int mode);```

To invoke, you would need to get the `MmapGpioInterface` from the `BoardInfo` instance via the `createMmapGpio` operation. There is an example here: https://github.com/mattjlewis/diozero/blob/main/diozero-sampleapps/src/main/java/com/diozero/sampleapps/perf/MmapGpioPerfTest.java#L60

**Comment by neil-benn** [comment]
Hello,

  Thanks; I'll take a look at it - struggling with trying to get a dd equivalent working on win 1- at the moment.  It used to work but now brings down PowerShell - grr!!

Cheers,

Neil

--

Neil Benn MSc
Ziath Ltd
Phone: +44 (0) 1223 855021
http://www.ziath.com<http://www.ziath.com/>

Please consider the environment before printing this email.

Follow us on Facebook<http://www.facebook.com/ziathltd>, Twitter<http://www.twitter.com/ziath_ltd> or LinkedIn<http://www.linkedin.com/company/ziath-ltd>

IMPORTANT NOTICE: This message, including any attached documents, is intended only for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify Ziath Ltd immediately by email at ***@***.******@***.***>. Thank you.

________________________________

**Comment by neil-benn** [comment]
Great thanks - I'll wrap this into our app code and update to test.  It'll be a few weeks as I'm off for a couple of weeks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
