### ISSUE TITLE
Missing activeHigh parameter from DebouncedDigitalInputDevice constructor

### ISSUE THREAD

**Issue by zixzix** [mattjlewis/diozero#93]
Hello mattjlewis
I'm starting to test the DebouncedDigitalInputDevice class. 
Until now I had implemented a function made by myself for debouncing but your solution looks better. 

However, I have noticed that I cannot specify the activeHigh value that I used often. 
Is it possible to add a new constructor that also specifies this parameter?

Thank you

**Comment by mattjlewis** [comment]
Apologies for the long delay on this one - finally released 1.3.4
